version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./private_keys:/app/private_keys
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: PAssword123.
      POSTGRES_DB: DWUV
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
